//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public long AplicacionId { get; set; }
        public Nullable<long> AplicacionIdPadre { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Controlador { get; set; }
        public string Accion { get; set; }
        public Nullable<int> EsMenu { get; set; }
        public Nullable<int> Orden { get; set; }
    }
}
