//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAM_Informe_Medico
    {
        public int informe_medico { get; set; }
        public Nullable<int> codigo_cliente { get; set; }
        public Nullable<int> codigo_mascota { get; set; }
        public Nullable<System.DateTime> fechaAtencion { get; set; }
        public string detalleInforme { get; set; }
        public string diagnostico { get; set; }
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
    }
}
