//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCP_Tipo_Documento
    {
        public GCP_Tipo_Documento()
        {
            this.GG_Persona = new HashSet<GG_Persona>();
        }
    
        public int tipo_documento { get; set; }
        public string descrDocumento { get; set; }
    
        public virtual ICollection<GG_Persona> GG_Persona { get; set; }
    }
}
