//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCP_Cliente
    {
        public GCP_Cliente()
        {
            this.GAM_Informe_Medico = new HashSet<GAM_Informe_Medico>();
            this.GCP_Mascota = new HashSet<GCP_Mascota>();
            this.GFC_Comprobante_Pago = new HashSet<GFC_Comprobante_Pago>();
            this.GPA_Solicitud_Cruces = new HashSet<GPA_Solicitud_Cruces>();
            this.GPA_Solicitud_Cruces1 = new HashSet<GPA_Solicitud_Cruces>();
            this.GPA_Solicitud = new HashSet<GPA_Solicitud>();
        }
    
        public int codigo_cliente { get; set; }
        public Nullable<int> codigo_persona { get; set; }
        public string emailCliente { get; set; }
        public Nullable<bool> autorizaUsoDatos { get; set; }
    
        public virtual ICollection<GAM_Informe_Medico> GAM_Informe_Medico { get; set; }
        public virtual GG_Persona GG_Persona { get; set; }
        public virtual ICollection<GCP_Mascota> GCP_Mascota { get; set; }
        public virtual ICollection<GFC_Comprobante_Pago> GFC_Comprobante_Pago { get; set; }
        public virtual ICollection<GPA_Solicitud_Cruces> GPA_Solicitud_Cruces { get; set; }
        public virtual ICollection<GPA_Solicitud_Cruces> GPA_Solicitud_Cruces1 { get; set; }
        public virtual ICollection<GPA_Solicitud> GPA_Solicitud { get; set; }
    }
}
