//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCP_Raza
    {
        public GCP_Raza()
        {
            this.GCP_Mascota = new HashSet<GCP_Mascota>();
        }
    
        public int codigo_raza { get; set; }
        public Nullable<int> codigo_especie { get; set; }
        public string nombreRaza { get; set; }
    
        public virtual ICollection<GCP_Mascota> GCP_Mascota { get; set; }
    }
}
