//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFC_Comprobante_Pago
    {
        public int comprobante_pago { get; set; }
        public Nullable<int> codigo_cliente { get; set; }
        public Nullable<int> nroComprobante { get; set; }
        public string descripcionItem { get; set; }
        public Nullable<System.DateTime> fechaComprobante { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public Nullable<decimal> igv { get; set; }
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
    }
}
