//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GG_Empleado
    {
        public GG_Empleado()
        {
            this.GPA_Solicitud = new HashSet<GPA_Solicitud>();
            this.GPA_Solicitud1 = new HashSet<GPA_Solicitud>();
        }
    
        public int codigo_empleado { get; set; }
        public Nullable<int> codigo_persona { get; set; }
        public string cargo { get; set; }
        public string area { get; set; }
    
        public virtual GG_Persona GG_Persona { get; set; }
        public virtual ICollection<GPA_Solicitud> GPA_Solicitud { get; set; }
        public virtual ICollection<GPA_Solicitud> GPA_Solicitud1 { get; set; }
    }
}
