//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GG_Persona
    {
        public GG_Persona()
        {
            this.GCP_Cliente = new HashSet<GCP_Cliente>();
            this.GG_Empleado = new HashSet<GG_Empleado>();
        }
    
        public int codigo_persona { get; set; }
        public Nullable<int> tipo_documento { get; set; }
        public string numeroDocumento { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string nombres { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<GCP_Cliente> GCP_Cliente { get; set; }
        public virtual GCP_Tipo_Documento GCP_Tipo_Documento { get; set; }
        public virtual ICollection<GG_Empleado> GG_Empleado { get; set; }
    }
}
