//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Solicitud_Adopcion
    {
        public int solicitud_adopcion { get; set; }
        public Nullable<int> numero_solicitud { get; set; }
        public Nullable<bool> domicilioLocal { get; set; }
    
        public virtual GPA_Solicitud GPA_Solicitud { get; set; }
    }
}
