//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Solicitud_Pedigri
    {
        public GPA_Solicitud_Pedigri()
        {
            this.GPA_Camada = new HashSet<GPA_Camada>();
        }
    
        public int solicitud_pedigri { get; set; }
        public Nullable<int> numero_solicitud { get; set; }
        public Nullable<int> codigo_mascota_padre { get; set; }
        public Nullable<int> codigo_mascota_madre { get; set; }
        public Nullable<System.DateTime> fechaRecepcionInf_KCP { get; set; }
    
        public virtual GCP_Mascota GCP_Mascota { get; set; }
        public virtual GCP_Mascota GCP_Mascota1 { get; set; }
        public virtual ICollection<GPA_Camada> GPA_Camada { get; set; }
        public virtual GPA_Solicitud GPA_Solicitud { get; set; }
    }
}
