//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Detalle_Resultados_KCP
    {
        public int detalle_resultados_KCP { get; set; }
        public Nullable<int> numero_registro_resultado_KCP { get; set; }
        public string numRegistroKCP { get; set; }
        public string descResultado { get; set; }
    
        public virtual GPA_Registro_Resultados_KCP GPA_Registro_Resultados_KCP { get; set; }
    }
}
