//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Solicitud_Cruces
    {
        public int solicitud_cruce { get; set; }
        public Nullable<int> numero_solicitud { get; set; }
        public Nullable<int> codigo_cliente1 { get; set; }
        public Nullable<int> codigo_mascota1 { get; set; }
        public Nullable<int> codigo_cliente2 { get; set; }
        public Nullable<int> codigo_mascota2 { get; set; }
        public Nullable<System.DateTime> fechaCruce { get; set; }
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public virtual GCP_Cliente GCP_Cliente1 { get; set; }
        public virtual GCP_Mascota GCP_Mascota { get; set; }
        public virtual GCP_Mascota GCP_Mascota1 { get; set; }
        public virtual GPA_Solicitud GPA_Solicitud { get; set; }
    }
}
