//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenterDL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Camada
    {
        public int numero_camada { get; set; }
        public Nullable<int> solicitud_pedigri { get; set; }
        public Nullable<int> codigo_mascota { get; set; }
    
        public virtual GPA_Solicitud_Pedigri GPA_Solicitud_Pedigri { get; set; }
    }
}
